name: Terraform Pipeline
#work flow dispatch
on:
  push:
    branches:
      - main
    paths:
      - 'go-web-app/Terraform/**'
  workflow_dispatch:

env:
  TF_WORKING_DIR: go-web-app/Terraform

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write   # for OIDC (recommended)
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 🔐 Configure AWS (NO hardcoded creds)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 🏗 Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # 🚀 Init
      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.TF_WORKING_DIR }}

      # ✅ Validate
      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ env.TF_WORKING_DIR }}

      # 📊 Plan
      - name: Terraform Plan
        run: terraform plan -input=false
        working-directory: ${{ env.TF_WORKING_DIR }}

      # 🚀 Apply (only on main branch)
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -input=false
        working-directory: ${{ env.TF_WORKING_DIR }}